questions = [
    "Do you like pineapple pizza?",
    "What does mango taste like to you?",
    "What’s the best gift you’ve received recently?",
    "Who do you love the most?",
    "How would you deal with an aggressive goose?",
    "Were you breastfed as a baby?",
    "What’s one advancement in society you’re thankful for?",
    "What are your top travel destinations?",
    "Which profession do you trust the most?",
    "How do you usually deal with flies at home?",
    "What’s your favorite animal?",
    "What's the scariest insect you’ve encountered?",
    "Have you ever broken a bone?",
    "Would you help someone if they tripped and fell?",
    "What's your go-to dessert?",
    "What would you do if aliens arrived on Earth?",
    "How long have you had your current phone?",
    "What’s something you usually donate or throw away?",
    "What’s a dance trend you’ve actually tried?",
    "Which age group do you find more pleasant to talk to?",
    "What do you dream about often?",
    "What's your favorite fictional couple?",
    "How long can you hold your breath?",
    "Where do you usually relax after a long day?",
    "What's the first word that comes to your mind when you're annoyed?",
    "Do you like to attend formal events?",
    "How much sleep do you usually get?",
    "Are you okay with making controversial jokes?",
    "What did you think about that history documentary?",
    "How would you handle a swarm of pests?",
    "Do you belong to any online communities?",
    "How do you feel about basic math?",
    "What's 2+3?",
    "Who’s the most well-known historical figure you can think of?",
    "Name a radioactive element.",
    "Where are you from?",
    "What's your favorite number?",
    "What's your favorite wild animal?",
    "Do you enjoy spicy food?",
    "What's a random number you like?",
    "Have you ever tasted baby food?",
    "What do you think about rainbows?",
    "Where are you spending the weekend?",
    "Do you post much online?",
    "Do you cook at home often?",
    "What's your favorite farm animal?",
    # ---
    "What’s your favorite way to spend a rainy day?",
    "Do you prefer coffee or tea?",
    "What’s the last movie that made you cry?",
    "How do you feel about public speaking?",
    "What's a skill you wish you had?",
    "What's your favorite season?",
    "Do you have any hidden talents?",
    "What’s the most interesting place you’ve ever visited?",
    "What's a book you think everyone should read?",
    "What's your least favorite chore?",
    "If you could have any superpower, what would it be?",
    "What's a food you could eat every day?",
    "How do you deal with stress?",
    "What’s the most embarrassing song on your playlist?",
    "What's a new hobby you’d like to try?",
    "What's your ideal vacation?",
    "Do you like to go to concerts?",
    "What's a piece of advice you’d give your younger self?",
    "What's your favorite board game?",
    "How do you usually get to work or school?",
    "What’s a language you’d love to learn?",
    "What's the best concert you've ever been to?",
    "What's a TV show you've binge-watched recently?",
    "Do you enjoy exercising?",
    "What's your most used emoji?",
    "What's your favorite holiday?",
    "Do you have a favorite plant or flower?",
    "What's the best compliment you've ever received?",
    "What’s a food you absolutely hate?",
    "What's your favorite time of day?",
    "What's a subject you were bad at in school?",
    "Do you prefer talking on the phone or texting?",
    "What's a celebrity you'd want to have dinner with?",
    "How do you feel about surprises?",
    "What's your favorite song to sing in the shower?",
    "What's the most unusual food you've ever tried?",
    "Do you prefer a quiet night in or a night out with friends?",
    "What’s a cartoon character you’ve always liked?",
    "What’s a weird habit you have?",
    "What's a historical event you find fascinating?",
    "What's your favorite type of weather?",
    "Do you believe in ghosts?",
    "What’s a common saying or phrase you dislike?",
    "What's a job you think you'd be terrible at?",
    "What’s your favorite piece of clothing?",
    "What's your first memory?",
    "What's the best gift you've ever given someone?",
    "What’s a movie you can watch over and over?",
    "Do you like to plan things out or be spontaneous?",
    "What's a word you overuse?",
]
